version: "3.9"

services:
  xrpld:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: qxrp_single
    restart: unless-stopped
    volumes:
      - ../cfg/standalone.cfg:/cfg/xrpld.cfg:ro
      - ../data/single:/data
    ports:
      - "5005:5005"
      - "51235:51235"
    command: ["--conf", "/cfg/xrpld.cfg", "--standalone"]
